AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/schema.rb'
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
