name: "exchange_rate - rspec"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: ./exchange_rate

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          ruby-version: '3.2.2'
          bundler-cache: true
          working-directory: ./exchange_rate
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: ./exchange_rate
      - name: Build project
        run: yarn install
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
